### ISSUE TITLE
ESLint flowtype/no-types-missing-file-annotation

### ISSUE THREAD

**Issue by VladaStechr** [yangshun/flow-scripts#4]
Hi, I'm getting flowtype/no-types-missing-file-annotation on generated file. Adding // @flow on top of the file helped. Or disabling ESLint with /* eslint-disable */ works fine too :). Maybe you can add option for this.

**Comment by yangshun** [comment]
Ah I see. I guess it's because you were linting the `flow-typed` directory also. Adding `/* eslint-disable */` is not a foolproof method because if the file gets generated again, that line will get wiped out.

The community stubs from `flow-typed` does not include `// @flow` at the top, hence it wouldn't make sense to do so for `flow-scripts` too.

A better way forward would be to exclude linting of the `flow-typed` directory. Thanks for the report nonetheless!
